### ISSUE TITLE
Do not use year-specific email addresses

### ISSUE THREAD

**Issue by novoid** [linuxtage/CoC#2]
I'd change any reference to year-specific email addresses such as `graz18@` to email addresses that are independent of the current year.

It just causes work and is therefore error-prone.

**Comment by meisterluk** [comment]
I can see the problem. De facto, `graz18@` is our main email address though. I'll keep this issue open.

**Comment by flowolf** [comment]
there actually is no need for the contact information in the CoC itself.
we can refer to the website or contact information in the program booklet.
